id: I61F8F08B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:08:17+00:00'
last_modified: '2022-06-08T16:41:50.363807+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21022
  title: གཏེར་ཆོས། ཆོས་སྐྱོང་གླིང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    846F:
      image_group_id: I1KG10214
      title: ''
      total_pages: 552
      order: 1
      base_file: 846F.txt
    9E03:
      image_group_id: I1KG10215
      title: ''
      total_pages: 572
      order: 2
      base_file: 9E03.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
